import { z } from "zod";
import {
  acceptDiaryInvite,
  adoptDiaryHighlightSuggestion,
  createDiaryInvite,
  createFamilyMilestone,
  createDiaryEvent,
  createEventComment,
  deleteDiaryEvent,
  deleteDiaryEventMedia,
  deleteFamilyMilestone,
  deletePhaseReflection,
  deleteAnnualReflection,
  generatePhaseReflection,
  generateAnnualReflection,
  getDiaryEventRevisions,
  getFullDiaryArchive,
  getDiaryAuditLogs,
  getDiaryMembers,
  getFamilyMilestones,
  getEventComments,
  getEventReactions,
  getDiarySnapshot,
  getDiaryOnThisDayMemories,
  importDiaryEvents,
  getSharedDiary,
  reorderDiaryEventMedia,
  reorderDiaryEvents,
  saveDiaryJourneyDetails,
  removeDiaryMember,
  restoreDiaryEventRevision,
  setDiaryEventVisibility,
  suggestDiaryHighlights,
  updateDiaryAiPreference,
  updateFamilyMilestone,
  updateDiaryEvent,
  updateDiaryEventMedia,
  updateDiaryPhaseBoundaries,
  updateDiaryProfile,
  updateDiarySharing,
  updateDiaryMemberRole,
  toggleEventReaction,
  updatePhaseReflection,
  uploadDiaryCoverImage,
  uploadDiaryEventImage,
  uploadDiaryLivePhotoMotion,
  uploadShareSafeDiaryImage,
  clearShareSafeDiaryImage,
  uploadDiaryVoiceNote,
  deleteDiaryVoiceNote,
} from "../db";
import { EVENT_COLORS, EVENT_TYPES, isSupportedAudioMimeType, isSupportedImageMimeType } from "../diaryHelpers";
import { protectedProcedure, publicProcedure, router } from "../_core/trpc";

const diaryEventInput = z.object({
  occurredAt: z.number().int().min(-2208988800000).max(4102444800000),
  datePrecision: z.enum(["day", "month", "year"]),
  eventType: z.enum(EVENT_TYPES),
  title: z.string().trim().min(1, "請為這段記憶寫下標題。").max(180),
  body: z.string().trim().max(8000),
  ageLabel: z.string().trim().max(80).optional().nullable(),
  place: z.string().trim().max(180).optional().nullable(),
  color: z.enum(EVENT_COLORS),
  tagNames: z.array(z.string().trim().max(24)).max(8),
  skillNames: z.array(z.string().trim().max(24)).max(8).default([]),
  track: z.enum(["career", "skills", "life", "hardware"]).default("life"),
  milestoneType: z.enum(["standard", "highlight", "turning_point", "gear_workflow", "reflection"]).default("standard"),
  milestoneWeight: z.number().int().min(1).max(5).default(1),
  comparisonGroup: z.string().trim().max(96).nullable().optional(),
  unlocksAt: z.number().int().min(0).max(4102444800000).nullable().optional(),
  phaseKeywords: z.array(z.string().trim().max(24)).max(8).default([]),
  mapLatitudeE6: z.number().int().min(-90_000_000).max(90_000_000).nullable().optional(),
  mapLongitudeE6: z.number().int().min(-180_000_000).max(180_000_000).nullable().optional(),
  locationPrivacy: z.enum(["none", "city", "precise"]).default("none"),
  soundtrackTitle: z.string().trim().max(120).nullable().optional(),
  soundtrackUrl: z.string().trim().url("請輸入有效的直接音訊網址。").max(1024).nullable().optional(),
  shareScope: z.enum(["private", "public", "link"]).default("private"),
});

const year = z.number().int().min(1900).max(2200).nullable().optional();
const familyMilestoneInput = z.object({ occurredAt: z.number().int().min(-2208988800000).max(4102444800000), datePrecision: z.enum(["day", "month", "year"]), title: z.string().trim().min(1).max(180), summary: z.string().trim().min(1).max(480), sourceEventId: z.number().int().positive().nullable() });

export const diaryRouter = router({
  get: protectedProcedure.input(z.object({ diaryId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => input?.diaryId ? getDiarySnapshot(ctx.user.id, input.diaryId) : getDiarySnapshot(ctx.user.id)),
  exportFullArchive: protectedProcedure.mutation(({ ctx }) => getFullDiaryArchive(ctx.user.id)),
  getOnThisDay: protectedProcedure.input(z.object({ diaryId: z.number().int().positive().optional(), year: z.number().int().min(1900).max(2200), month: z.number().int().min(1).max(12), day: z.number().int().min(1).max(31), timezoneOffsetMinutes: z.number().int().min(-840).max(840) })).query(({ ctx, input }) => getDiaryOnThisDayMemories(ctx.user.id, input)),
  createEvent: protectedProcedure.input(diaryEventInput.extend({ diaryId: z.number().int().positive().optional() })).mutation(({ ctx, input }) => {
    const { diaryId, ...event } = input;
    return diaryId ? createDiaryEvent(ctx.user.id, event, diaryId) : createDiaryEvent(ctx.user.id, event);
  }),
  importEvents: protectedProcedure.input(z.object({ diaryId: z.number().int().positive().optional(), events: z.array(diaryEventInput).min(1).max(250) })).mutation(({ ctx, input }) => input.diaryId ? importDiaryEvents(ctx.user.id, input.events, input.diaryId) : importDiaryEvents(ctx.user.id, input.events)),
  updateEvent: protectedProcedure.input(diaryEventInput.extend({ id: z.number().int().positive() })).mutation(({ ctx, input }) => {
    const { id, ...event } = input;
    return updateDiaryEvent(ctx.user.id, id, event);
  }),
  getEventRevisions: protectedProcedure.input(z.object({ eventId: z.number().int().positive() })).query(({ ctx, input }) => getDiaryEventRevisions(ctx.user.id, input.eventId)),
  getEventComments: protectedProcedure.input(z.object({ eventId: z.number().int().positive() })).query(({ ctx, input }) => getEventComments(ctx.user.id, input.eventId)),
  getEventReactions: protectedProcedure.input(z.object({ eventId: z.number().int().positive() })).query(({ ctx, input }) => getEventReactions(ctx.user.id, input.eventId)),
  getFamilyMembers: protectedProcedure.query(({ ctx }) => getDiaryMembers(ctx.user.id)),
  getFamilyAudit: protectedProcedure.query(({ ctx }) => getDiaryAuditLogs(ctx.user.id)),
  getFamilyMilestones: protectedProcedure.input(z.object({ diaryId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => getFamilyMilestones(ctx.user.id, input?.diaryId)),
  createFamilyMilestone: protectedProcedure.input(familyMilestoneInput).mutation(({ ctx, input }) => createFamilyMilestone(ctx.user.id, input)),
  updateFamilyMilestone: protectedProcedure.input(familyMilestoneInput.extend({ id: z.number().int().positive() })).mutation(({ ctx, input }) => { const { id, ...milestone } = input; return updateFamilyMilestone(ctx.user.id, id, milestone); }),
  deleteFamilyMilestone: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => deleteFamilyMilestone(ctx.user.id, input.id)),
  removeFamilyMember: protectedProcedure.input(z.object({ memberId: z.number().int().positive() })).mutation(({ ctx, input }) => removeDiaryMember(ctx.user.id, input.memberId)),
  updateFamilyMemberRole: protectedProcedure.input(z.object({ memberId: z.number().int().positive(), role: z.enum(["editor", "commenter"]) })).mutation(({ ctx, input }) => updateDiaryMemberRole(ctx.user.id, input.memberId, input.role)),
  createEventComment: protectedProcedure.input(z.object({ eventId: z.number().int().positive(), body: z.string().trim().min(1).max(2000) })).mutation(({ ctx, input }) => createEventComment(ctx.user.id, input.eventId, input.body)),
  toggleEventReaction: protectedProcedure.input(z.object({ eventId: z.number().int().positive(), reaction: z.enum(["heart", "spark", "celebrate", "support"]) })).mutation(({ ctx, input }) => toggleEventReaction(ctx.user.id, input.eventId, input.reaction)),
  createFamilyInvite: protectedProcedure.input(z.object({ email: z.string().trim().email().max(320), role: z.enum(["editor", "commenter"]), expiresAt: z.number().int().min(Date.now() + 60_000).max(4102444800000) })).mutation(({ ctx, input }) => createDiaryInvite(ctx.user.id, input)),
  acceptFamilyInvite: protectedProcedure.input(z.object({ token: z.string().trim().min(16).max(128) })).mutation(({ ctx, input }) => acceptDiaryInvite(ctx.user.id, ctx.user.email, input.token)),
  restoreEventRevision: protectedProcedure.input(z.object({ eventId: z.number().int().positive(), revisionId: z.number().int().positive() })).mutation(({ ctx, input }) => restoreDiaryEventRevision(ctx.user.id, input.eventId, input.revisionId)),
  deleteEvent: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => deleteDiaryEvent(ctx.user.id, input.id)),
  setEventVisibility: protectedProcedure.input(z.object({ id: z.number().int().positive(), shareScope: z.enum(["private", "public", "link"]) })).mutation(({ ctx, input }) => setDiaryEventVisibility(ctx.user.id, input.id, input.shareScope)),
  reorderEvents: protectedProcedure.input(z.object({ diaryId: z.number().int().positive().optional(), eventIds: z.array(z.number().int().positive()).max(500) })).mutation(({ ctx, input }) => input.diaryId ? reorderDiaryEvents(ctx.user.id, input.eventIds, input.diaryId) : reorderDiaryEvents(ctx.user.id, input.eventIds)),
  updatePhaseBoundaries: protectedProcedure.input(z.object({
    childhoodStartYear: year,
    childhoodEndYear: year,
    educationStartYear: year,
    educationEndYear: year,
    careerStartYear: year,
    careerEndYear: year,
  })).mutation(({ ctx, input }) => updateDiaryPhaseBoundaries(ctx.user.id, input)),
  generatePhaseReflection: protectedProcedure.input(z.object({ phaseKey: z.enum(["childhood", "education", "career"]) })).mutation(({ ctx, input }) => generatePhaseReflection(ctx.user.id, input.phaseKey)),
  generateAnnualReflection: protectedProcedure.input(z.object({
    year: z.number().int().min(1900).max(2200),
    confirmAiProcessing: z.boolean().refine((value) => value, "請先確認只會將此年度事件內容送往 AI 生成回顧。"),
  })).mutation(({ ctx, input }) => generateAnnualReflection(ctx.user.id, input.year)),
  suggestHighlights: protectedProcedure.input(z.object({
    confirmAiProcessing: z.boolean().refine((value) => value, "請先確認只會將 private 事件片段送往 AI 產生候選。"),
  })).mutation(({ ctx }) => suggestDiaryHighlights(ctx.user.id)),
  adoptHighlightSuggestion: protectedProcedure.input(z.object({ eventId: z.number().int().positive() })).mutation(({ ctx, input }) => adoptDiaryHighlightSuggestion(ctx.user.id, input.eventId)),
  updatePhaseReflection: protectedProcedure.input(z.object({ phaseKey: z.enum(["childhood", "education", "career"]), recap: z.string().trim().min(1).max(3000), reflection: z.string().trim().min(1).max(3000) })).mutation(({ ctx, input }) => updatePhaseReflection(ctx.user.id, input)),
  updateAiPreference: protectedProcedure.input(z.object({ aiEnabled: z.boolean() })).mutation(({ ctx, input }) => updateDiaryAiPreference(ctx.user.id, input.aiEnabled)),
  updateProfile: protectedProcedure.input(z.object({
    title: z.string().trim().min(1, "請為這本成長史保留一個標題。").max(160),
    subtitle: z.string().trim().max(240).nullable().optional(),
  })).mutation(({ ctx, input }) => updateDiaryProfile(ctx.user.id, input)),
  deletePhaseReflection: protectedProcedure.input(z.object({ phaseKey: z.enum(["childhood", "education", "career"]) })).mutation(({ ctx, input }) => deletePhaseReflection(ctx.user.id, input.phaseKey)),
  deleteAnnualReflection: protectedProcedure.input(z.object({ year: z.number().int().min(1900).max(2200) })).mutation(({ ctx, input }) => deleteAnnualReflection(ctx.user.id, input.year)),
  updateSharing: protectedProcedure.input(z.object({
    shareMode: z.enum(["private", "public", "link"]),
    birthYear: year,
    educationStartYear: year,
    careerStartYear: year,
    childhoodStartYear: year,
    childhoodEndYear: year,
    educationEndYear: year,
    careerEndYear: year,
    sharePassword: z.string().min(8, "分享密碼至少需要 8 個字元。").max(128).nullable().optional(),
    clearSharePassword: z.boolean().optional(),
    shareExpiresAt: z.number().int().min(0).max(4102444800000).nullable().optional(),
    regenerateLink: z.boolean().optional(),
    publicCoverTitle: z.string().trim().max(160).nullable().optional(),
    publicStoryLayout: z.enum(["editorial", "gallery", "minimal"]).optional(),
    clearPublicCover: z.boolean().optional(),
  })).mutation(({ ctx, input }) => updateDiarySharing(ctx.user.id, input)),
  uploadImage: protectedProcedure.input(z.object({
    eventId: z.number().int().positive(),
    fileName: z.string().trim().min(1).max(180),
    mimeType: z.string().trim().refine(isSupportedImageMimeType, "只支援 JPG、PNG、WebP 或 GIF 圖片。"),
    base64: z.string().min(1).max(6_000_000),
    caption: z.string().trim().max(240).optional(),
  })).mutation(({ ctx, input }) => uploadDiaryEventImage({ userId: ctx.user.id, ...input })),
  uploadLivePhotoMotion: protectedProcedure.input(z.object({
    eventId: z.number().int().positive(),
    fileName: z.string().trim().min(1).max(180),
    mimeType: z.literal("video/quicktime"),
    base64: z.string().min(1).max(6_000_000),
  })).mutation(({ ctx, input }) => uploadDiaryLivePhotoMotion({ userId: ctx.user.id, ...input })),
  uploadShareSafeImage: protectedProcedure.input(z.object({
    mediaId: z.number().int().positive(),
    fileName: z.string().trim().min(1).max(180),
    mimeType: z.enum(["image/jpeg", "image/png", "image/webp"]),
    base64: z.string().min(1).max(6_000_000),
  })).mutation(({ ctx, input }) => uploadShareSafeDiaryImage({ userId: ctx.user.id, ...input })),
  clearShareSafeImage: protectedProcedure.input(z.object({ mediaId: z.number().int().positive() })).mutation(({ ctx, input }) => clearShareSafeDiaryImage(ctx.user.id, input.mediaId)),
  updateImage: protectedProcedure.input(z.object({ id: z.number().int().positive(), caption: z.string().trim().max(240).nullable() })).mutation(({ ctx, input }) => updateDiaryEventMedia(ctx.user.id, input.id, input.caption)),
  reorderImages: protectedProcedure.input(z.object({ eventId: z.number().int().positive(), mediaIds: z.array(z.number().int().positive()).max(100) })).mutation(({ ctx, input }) => reorderDiaryEventMedia(ctx.user.id, input.eventId, input.mediaIds)),
  uploadCoverImage: protectedProcedure.input(z.object({
    fileName: z.string().trim().min(1).max(180),
    mimeType: z.string().trim().refine(isSupportedImageMimeType, "只支援 JPG、PNG、WebP 或 GIF 圖片。"),
    base64: z.string().min(1).max(6_000_000),
  })).mutation(({ ctx, input }) => uploadDiaryCoverImage({ userId: ctx.user.id, ...input })),
  uploadVoiceNote: protectedProcedure.input(z.object({
    eventId: z.number().int().positive(),
    fileName: z.string().trim().min(1).max(180),
    mimeType: z.string().trim().refine(isSupportedAudioMimeType, "只支援 WebM、MP3、WAV、OGG 或 M4A 音檔。"),
    base64: z.string().min(1).max(22_500_000),
    durationMs: z.number().int().min(0).max(14_400_000).nullable().optional(),
    language: z.string().trim().regex(/^[a-z]{2,3}$/i, "請使用 ISO 語言代碼，例如 zh 或 en。" ).max(3).optional(),
    confirmAiProcessing: z.boolean().refine((value) => value, "請先確認本次錄音會送往語音轉寫服務。"),
  })).mutation(({ ctx, input }) => uploadDiaryVoiceNote({ userId: ctx.user.id, ...input })),
  deleteVoiceNote: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => deleteDiaryVoiceNote(ctx.user.id, input.id)),
  deleteImage: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => deleteDiaryEventMedia(ctx.user.id, input.id)),
  saveJourneyDetails: protectedProcedure.input(z.object({
    eventId: z.number().int().positive(),
    startedAt: z.number().int().min(-2208988800000).max(4102444800000),
    endedAt: z.number().int().min(-2208988800000).max(4102444800000),
    coverMediaId: z.number().int().positive().nullable(),
  }).refine((input) => input.startedAt <= input.endedAt, "旅程起訖日期無效。")).mutation(({ ctx, input }) => { const { eventId, ...details } = input; return saveDiaryJourneyDetails(ctx.user.id, eventId, details); }),
});

export const shareRouter = router({
  get: publicProcedure.input(z.object({ slug: z.string().trim().regex(/^story-[a-z0-9-]+$/), token: z.string().trim().min(16).max(128).optional(), password: z.string().min(1).max(128).optional() })).query(({ input }) => getSharedDiary(input.slug, input.token, input.password)),
});
