import { z } from "zod";
import {
  acceptDiaryInvite,
  createDiaryInvite,
  createDiaryEvent,
  createEventComment,
  deleteDiaryEvent,
  deleteDiaryEventMedia,
  deletePhaseReflection,
  deleteAnnualReflection,
  generatePhaseReflection,
  generateAnnualReflection,
  getDiaryEventRevisions,
  getDiaryAuditLogs,
  getDiaryMembers,
  getEventComments,
  getDiarySnapshot,
  importDiaryEvents,
  getSharedDiary,
  reorderDiaryEventMedia,
  reorderDiaryEvents,
  removeDiaryMember,
  restoreDiaryEventRevision,
  setDiaryEventVisibility,
  updateDiaryAiPreference,
  updateDiaryEvent,
  updateDiaryEventMedia,
  updateDiaryPhaseBoundaries,
  updateDiaryProfile,
  updateDiarySharing,
  updateDiaryMemberRole,
  updatePhaseReflection,
  uploadDiaryCoverImage,
  uploadDiaryEventImage,
} from "../db";
import { EVENT_COLORS, EVENT_TYPES, isSupportedImageMimeType } from "../diaryHelpers";
import { protectedProcedure, publicProcedure, router } from "../_core/trpc";

const diaryEventInput = z.object({
  occurredAt: z.number().int().min(-2208988800000).max(4102444800000),
  datePrecision: z.enum(["day", "month", "year"]),
  eventType: z.enum(EVENT_TYPES),
  title: z.string().trim().min(1, "請為這段記憶寫下標題。").max(180),
  body: z.string().trim().max(8000),
  ageLabel: z.string().trim().max(80).optional().nullable(),
  place: z.string().trim().max(180).optional().nullable(),
  color: z.enum(EVENT_COLORS),
  tagNames: z.array(z.string().trim().max(24)).max(8),
  skillNames: z.array(z.string().trim().max(24)).max(8).default([]),
  track: z.enum(["career", "skills", "life", "hardware"]).default("life"),
  milestoneType: z.enum(["standard", "highlight", "turning_point", "gear_workflow", "reflection"]).default("standard"),
  milestoneWeight: z.number().int().min(1).max(5).default(1),
  comparisonGroup: z.string().trim().max(96).nullable().optional(),
  unlocksAt: z.number().int().min(0).max(4102444800000).nullable().optional(),
  phaseKeywords: z.array(z.string().trim().max(24)).max(8).default([]),
  mapLatitudeE6: z.number().int().min(-90_000_000).max(90_000_000).nullable().optional(),
  mapLongitudeE6: z.number().int().min(-180_000_000).max(180_000_000).nullable().optional(),
  locationPrivacy: z.enum(["none", "city", "precise"]).default("none"),
});

const year = z.number().int().min(1900).max(2200).nullable().optional();

export const diaryRouter = router({
  get: protectedProcedure.input(z.object({ diaryId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => input?.diaryId ? getDiarySnapshot(ctx.user.id, input.diaryId) : getDiarySnapshot(ctx.user.id)),
  createEvent: protectedProcedure.input(diaryEventInput.extend({ diaryId: z.number().int().positive().optional() })).mutation(({ ctx, input }) => {
    const { diaryId, ...event } = input;
    return diaryId ? createDiaryEvent(ctx.user.id, event, diaryId) : createDiaryEvent(ctx.user.id, event);
  }),
  importEvents: protectedProcedure.input(z.object({ diaryId: z.number().int().positive().optional(), events: z.array(diaryEventInput).min(1).max(250) })).mutation(({ ctx, input }) => input.diaryId ? importDiaryEvents(ctx.user.id, input.events, input.diaryId) : importDiaryEvents(ctx.user.id, input.events)),
  updateEvent: protectedProcedure.input(diaryEventInput.extend({ id: z.number().int().positive() })).mutation(({ ctx, input }) => {
    const { id, ...event } = input;
    return updateDiaryEvent(ctx.user.id, id, event);
  }),
  getEventRevisions: protectedProcedure.input(z.object({ eventId: z.number().int().positive() })).query(({ ctx, input }) => getDiaryEventRevisions(ctx.user.id, input.eventId)),
  getEventComments: protectedProcedure.input(z.object({ eventId: z.number().int().positive() })).query(({ ctx, input }) => getEventComments(ctx.user.id, input.eventId)),
  getFamilyMembers: protectedProcedure.query(({ ctx }) => getDiaryMembers(ctx.user.id)),
  getFamilyAudit: protectedProcedure.query(({ ctx }) => getDiaryAuditLogs(ctx.user.id)),
  removeFamilyMember: protectedProcedure.input(z.object({ memberId: z.number().int().positive() })).mutation(({ ctx, input }) => removeDiaryMember(ctx.user.id, input.memberId)),
  updateFamilyMemberRole: protectedProcedure.input(z.object({ memberId: z.number().int().positive(), role: z.enum(["editor", "commenter"]) })).mutation(({ ctx, input }) => updateDiaryMemberRole(ctx.user.id, input.memberId, input.role)),
  createEventComment: protectedProcedure.input(z.object({ eventId: z.number().int().positive(), body: z.string().trim().min(1).max(2000) })).mutation(({ ctx, input }) => createEventComment(ctx.user.id, input.eventId, input.body)),
  createFamilyInvite: protectedProcedure.input(z.object({ email: z.string().trim().email().max(320), role: z.enum(["editor", "commenter"]), expiresAt: z.number().int().min(Date.now() + 60_000).max(4102444800000) })).mutation(({ ctx, input }) => createDiaryInvite(ctx.user.id, input)),
  acceptFamilyInvite: protectedProcedure.input(z.object({ token: z.string().trim().min(16).max(128) })).mutation(({ ctx, input }) => acceptDiaryInvite(ctx.user.id, ctx.user.email, input.token)),
  restoreEventRevision: protectedProcedure.input(z.object({ eventId: z.number().int().positive(), revisionId: z.number().int().positive() })).mutation(({ ctx, input }) => restoreDiaryEventRevision(ctx.user.id, input.eventId, input.revisionId)),
  deleteEvent: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => deleteDiaryEvent(ctx.user.id, input.id)),
  setEventVisibility: protectedProcedure.input(z.object({ id: z.number().int().positive(), isPublic: z.boolean() })).mutation(({ ctx, input }) => setDiaryEventVisibility(ctx.user.id, input.id, input.isPublic)),
  reorderEvents: protectedProcedure.input(z.object({ diaryId: z.number().int().positive().optional(), eventIds: z.array(z.number().int().positive()).max(500) })).mutation(({ ctx, input }) => input.diaryId ? reorderDiaryEvents(ctx.user.id, input.eventIds, input.diaryId) : reorderDiaryEvents(ctx.user.id, input.eventIds)),
  updatePhaseBoundaries: protectedProcedure.input(z.object({
    childhoodStartYear: year,
    childhoodEndYear: year,
    educationStartYear: year,
    educationEndYear: year,
    careerStartYear: year,
    careerEndYear: year,
  })).mutation(({ ctx, input }) => updateDiaryPhaseBoundaries(ctx.user.id, input)),
  generatePhaseReflection: protectedProcedure.input(z.object({ phaseKey: z.enum(["childhood", "education", "career"]) })).mutation(({ ctx, input }) => generatePhaseReflection(ctx.user.id, input.phaseKey)),
  generateAnnualReflection: protectedProcedure.input(z.object({ year: z.number().int().min(1900).max(2200) })).mutation(({ ctx, input }) => generateAnnualReflection(ctx.user.id, input.year)),
  updatePhaseReflection: protectedProcedure.input(z.object({ phaseKey: z.enum(["childhood", "education", "career"]), recap: z.string().trim().min(1).max(3000), reflection: z.string().trim().min(1).max(3000) })).mutation(({ ctx, input }) => updatePhaseReflection(ctx.user.id, input)),
  updateAiPreference: protectedProcedure.input(z.object({ aiEnabled: z.boolean() })).mutation(({ ctx, input }) => updateDiaryAiPreference(ctx.user.id, input.aiEnabled)),
  updateProfile: protectedProcedure.input(z.object({
    title: z.string().trim().min(1, "請為這本成長史保留一個標題。").max(160),
    subtitle: z.string().trim().max(240).nullable().optional(),
  })).mutation(({ ctx, input }) => updateDiaryProfile(ctx.user.id, input)),
  deletePhaseReflection: protectedProcedure.input(z.object({ phaseKey: z.enum(["childhood", "education", "career"]) })).mutation(({ ctx, input }) => deletePhaseReflection(ctx.user.id, input.phaseKey)),
  deleteAnnualReflection: protectedProcedure.input(z.object({ year: z.number().int().min(1900).max(2200) })).mutation(({ ctx, input }) => deleteAnnualReflection(ctx.user.id, input.year)),
  updateSharing: protectedProcedure.input(z.object({
    shareMode: z.enum(["private", "public", "link"]),
    birthYear: year,
    educationStartYear: year,
    careerStartYear: year,
    childhoodStartYear: year,
    childhoodEndYear: year,
    educationEndYear: year,
    careerEndYear: year,
    sharePassword: z.string().min(8, "分享密碼至少需要 8 個字元。").max(128).nullable().optional(),
    clearSharePassword: z.boolean().optional(),
    shareExpiresAt: z.number().int().min(0).max(4102444800000).nullable().optional(),
    regenerateLink: z.boolean().optional(),
    publicCoverTitle: z.string().trim().max(160).nullable().optional(),
    publicStoryLayout: z.enum(["editorial", "gallery", "minimal"]).optional(),
    clearPublicCover: z.boolean().optional(),
  })).mutation(({ ctx, input }) => updateDiarySharing(ctx.user.id, input)),
  uploadImage: protectedProcedure.input(z.object({
    eventId: z.number().int().positive(),
    fileName: z.string().trim().min(1).max(180),
    mimeType: z.string().trim().refine(isSupportedImageMimeType, "只支援 JPG、PNG、WebP 或 GIF 圖片。"),
    base64: z.string().min(1).max(6_000_000),
    caption: z.string().trim().max(240).optional(),
  })).mutation(({ ctx, input }) => uploadDiaryEventImage({ userId: ctx.user.id, ...input })),
  updateImage: protectedProcedure.input(z.object({ id: z.number().int().positive(), caption: z.string().trim().max(240).nullable() })).mutation(({ ctx, input }) => updateDiaryEventMedia(ctx.user.id, input.id, input.caption)),
  reorderImages: protectedProcedure.input(z.object({ eventId: z.number().int().positive(), mediaIds: z.array(z.number().int().positive()).max(100) })).mutation(({ ctx, input }) => reorderDiaryEventMedia(ctx.user.id, input.eventId, input.mediaIds)),
  uploadCoverImage: protectedProcedure.input(z.object({
    fileName: z.string().trim().min(1).max(180),
    mimeType: z.string().trim().refine(isSupportedImageMimeType, "只支援 JPG、PNG、WebP 或 GIF 圖片。"),
    base64: z.string().min(1).max(6_000_000),
  })).mutation(({ ctx, input }) => uploadDiaryCoverImage({ userId: ctx.user.id, ...input })),
  deleteImage: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => deleteDiaryEventMedia(ctx.user.id, input.id)),
});

export const shareRouter = router({
  get: publicProcedure.input(z.object({ slug: z.string().trim().regex(/^story-[a-z0-9-]+$/), token: z.string().trim().min(16).max(128).optional(), password: z.string().min(1).max(128).optional() })).query(({ input }) => getSharedDiary(input.slug, input.token, input.password)),
});
